### ISSUE TITLE
No response of CrazyRadio after roslaunch

### ISSUE THREAD

**Issue by byronxubin** [USC-ACTLab/crazyflie_ros#1]
Hi guys,

I know the crazyswarm_master branch is the improved ROS package for the Crazyflie. After updated the firmware and Crazyradio, I wanted to test this new package a bit although I did not have the Vicon Mocap system. But the outcome is quite frustrating, the Crazyradio have no response after I have launch `hover_vicon.launch` in the folder `crazyflie_manager`, which works if I use the original crazyflie_ros package. I have modified the launch file a little bit, like changing the uri to align with my crazyflie. I also have tested on another folder `crazyswarm`, it does not work either. Really have no idea about this issue.

Since my lab uses Optitrack Mocap System, I would also need to modify the launch file about that. But this time, the approach used in this package seems quite different from before. I really have no idea about how to modify this time. If you could explain this for me, that would be greatly appreciated. 

Thanks.

**Comment by whoenig** [comment]
This package currently only works with the crazyswarm_package (`roslaunch crazyswarm hover_swarm.launch`). If you have optitrack, you need to adjust the file here to switch from vicon to optitrack: https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/launch/hover_swarm.launch#L54-L58

**Comment by byronxubin** [comment]
Okay, I've also tried `roslaunch crazyswarm hover_swarm.launch`. The crazyradio still has no response after `roslaunch`. I cannot find anywhere in launch file that adds crazyflie. And I have no idea about where to modify the uri to connect to my crazyflie. I once changed the uri of crazyflie and the radio address is `radio:=//0/90/2M/E7E7E7E700`. In `all49.yaml`, the address starts from `E7E7E7E701`. Would that be an issue if my address starts from `E7E7E7E700`? And what is these two lines used? [https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/launch/hover_swarm.launch#L10-L11](url)

Thanks.

**Comment by whoenig** [comment]
* `all49.yaml` contains the list of all CFs you have. You can enable/disable them, run battery checks, reboot etc. by running `python chooser.py` in `ros_ws/src/crazyswarm/scripts/chooser.py`.
* The address must be of the format `E7E7E7E7<X>`, where `<X>` is the hexadecimal representation of your crazyflie id. For example, `cf10` must have address `E7E7E7E70A`. The datarate should be 2M and the channel can be configured in `all49.yaml`.
* The two lines you point to is the broadcasting address. I believe this is baked into the firmware, so there shouldn't be a need to change.
